version: '1'

services:
  appsearch:
    image: docker.elastic.co/app-search/app-search:7.6.2
    environment:
      - "elasticsearch.host=http://elasticsearch:9200"
      - "allow_es_settings_modification=true"
      - "JAVA_OPTS=-Xmx512m -Xms512m"
    ports:
      - "3002:3002"
    networks:
      - es-net

networks:
  es-net:
    external: true