version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: search-ui
    networks:
      - es-network
    env_file:
      - prod.env


networks:
  es-network:
    external : true