# docker-compose.yml
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-react
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html
    depends_on:
      - react-app

  react-app:
    build:
      context: .
      dockerfile: Dockerfile  # Replace with the path to your React app Dockerfile
    environment:
      - NODE_ENV=production


# version: '3'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     container_name: search-ui