version: '3'
services:
  es-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    environment:
      - node.name=es-node1
      - discovery.seed_hosts=es-node2
      - cluster.initial_master_nodes=es-node1,es-node2
      - cluster.name=my-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false  # Disable X-Pack Security
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
    volumes:
      - ./es_data_1:/var/lib/elasticsearch/data
    networks:
      - es-net

  es-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    depends_on:
      - es-node1
    environment:
      - node.name=es-node2
      - discovery.seed_hosts=es-node1
      - cluster.initial_master_nodes=es-node1,es-node2
      - cluster.name=my-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false  # Disable X-Pack Security
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - es-net
    volumes:
      - ./es_data_2:/var/lib/elasticsearch/data
    
networks:
  es-net:
    external: true
